addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.5.4")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"   % "0.5.3")
addSbtPlugin("io.spray"         % "sbt-revolver"  % "0.9.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "2.3.1")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"  % "2.1.3")
