name: CI
on: [ push ]
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up sbt
        uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.8.0

      - name: Cache sbt and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt', '**/build.properties') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Format check & compile
        run: |
          cd forex-mtl
          sbt scalafmtCheckAll
          sbt compile